import { Booth } from '@/types';

// Mock 부스 데이터
export const mockBooths: Booth[] = [
  {
    boothId: 1,
    boothName: '치킨 부스',
    description: '바삭한 치킨과 시원한 맥주',
    universityName: '서울대학교',
    status: 'OPEN',
    capacity: 50,
    currentPeople: 30,
    totalWaiting: 52,
    estimatedWaitTime: 30,
  },
  {
    boothId: 2,
    boothName: '떡볶이 부스',
    description: '매콤달콤 떡볶이',
    universityName: '서울대학교',
    status: 'OPEN',
    capacity: 30,
    currentPeople: 15,
    totalWaiting: 23,
    estimatedWaitTime: 15,
  },
  {
    boothId: 3,
    boothName: '타로 점집',
    description: '당신의 미래를 알려드립니다',
    universityName: '서울대학교',
    status: 'OPEN',
    capacity: 5,
    currentPeople: 3,
    totalWaiting: 87,
    estimatedWaitTime: 60,
  },
  {
    boothId: 4,
    boothName: '포토부스',
    description: '인생샷 남기세요',
    universityName: '서울대학교',
    status: 'OPEN',
    capacity: 10,
    currentPeople: 8,
    totalWaiting: 45,
    estimatedWaitTime: 25,
  },
  {
    boothId: 5,
    boothName: '보드게임 카페',
    description: '친구들과 즐거운 시간',
    universityName: '서울대학교',
    status: 'CLOSED',
    capacity: 20,
    currentPeople: 0,
    totalWaiting: 0,
    estimatedWaitTime: 0,
  },
];
